// const moment = require("moment-timezone");
// const dateThailand = moment.tz(Date.now(), "Asia/Bangkok");

module.exports = (mongoose) => {
  var schema = mongoose.Schema(
    {
      _id: { type: mongoose.Schema.Types.ObjectId, auto: true },
      mru: { type: String, default: "" },
      mruname: { type: String, default: "" },
      readnumber: { type: String, default: "" },
      ca: { type: String, default: "" },
      install: { type: String, default: "" },
      name: { type: String, default: "" },
      address: { type: String, default: "" },
      peano: { type: String, default: "" },
      producer: { type: String, default: "" },
      type: { type: String, default: "" },
      phase: { type: String, default: "" },
      amp: { type: String, default: "" },
      firstinstall: { type: String, default: "" },
      dateinstall: { type: String, default: "" },
      value: { type: String, default: "" },
      code: { type: String, default: "" },
      unitintall: { type: String, default: "" },
      causeinstall: { type: String, default: "" },
      apptype: { type: String, default: "" },
      I_N: { type: String, default: "" },
      I_A: { type: String, default: "" },
      I_B: { type: String, default: "" },
      I_C: { type: String, default: "" },
      V_AN: { type: String, default: "" },
      V_BN: { type: String, default: "" },
      V_CN: { type: String, default: "" },
      PF_A: { type: String, default: "" },
      PF_B: { type: String, default: "" },
      PF_C: { type: String, default: "" },
      P_A: { type: String, default: "" },
      P_B: { type: String, default: "" },
      P_C: { type: String, default: "" },
      P_TOT: { type: String, default: "" },
      P_TOT_K: { type: String, default: "" },
      Q_A: { type: String, default: "" },
      Q_B: { type: String, default: "" },
      Q_C: { type: String, default: "" },
      Q_TOT: { type: String, default: "" },
      Q_TOT_K: { type: String, default: "" },
      S_A: { type: String, default: "" },
      S_B: { type: String, default: "" },
      S_C: { type: String, default: "" },
      S_TOT: { type: String, default: "" },
      S_TOT_K: { type: String, default: "" },
      E_P_A: { type: String, default: "" },
      E_P_B: { type: String, default: "" },
      E_P_C: { type: String, default: "" },
      E_P_TOT: { type: String, default: "" },
      E_P_TOT_K: { type: String, default: "" },
      E_Q_A: { type: String, default: "" },
      E_Q_B: { type: String, default: "" },
      E_Q_C: { type: String, default: "" },
      E_Q_TOT: { type: String, default: "" },
      E_Q_TOT_K: { type: String, default: "" },
      PF_SYS: { type: String, default: "" },
      FREQ: { type: String, default: "" },
      THD_I: { type: String, default: "" },
      THD_V: { type: String, default: "" },
      UNB_I: { type: String, default: "" },
      UNB_V: { type: String, default: "" },
      MT_SIZE: { type: String, default: "" },
      MT_REV_SPEC: { type: String, default: "" },
      CT_SIZE: { type: String, default: "" },
      CT_RATIO: { type: String, default: "" },
      P_TOT_C093: { type: String, default: "" },
      Q_TOT_C193: { type: String, default: "" },
      E_P_TOT_IMP: { type: String, default: "" },
      E_Q_TOT_IMP: { type: String, default: "" },
      LF_EST: { type: String, default: "" },
      UNIT_EST: { type: String, default: "" },
      INSP_ROUND: { type: String, default: "" },
      INSP_TIME: { type: String, default: "" },
      ERR_MT_A: { type: String, default: "" },
      ERR_MT_TOT: { type: String, default: "" },
      ERR_CT_BA: { type: String, default: "" },
      RESULT_MT: { type: String, default: "" },
      RESULT_CT: { type: String, default: "" },
      MONITOR_MT1: { type: String, default: "" },
      MONITOR_MT2: { type: String, default: "" },
      MONITOR_CT1: { type: String, default: "" },
      MONITOR_CT2: { type: String, default: "" },
      RESET_TIME: { type: String, default: "" },
      PMAC_NO: { type: String, default: "" },
      Username: { type: String, default: "" },
      full_name: { type: String, default: "" },
      DepartmentShortName: { type: String, default: "" },
      DepartmentFullName: { type: String, default: "" },
      CostCenterCode: { type: String, default: "" },
      CostCenterName: { type: String, default: "" },
      BaName: { type: String, default: "" },
      Peacode: { type: String, default: "" },
      Peaname: { type: String, default: "" },
      Lat: { type: String, default: "" },
      Long: { type: String, default: "" },
      sign_1: { type: String, default: "" },
      sign_2: { type: String, default: "" },
      createdAt: { type: Date, default: Date.now },
    },
    { _id: false }
  );
  schema.method("toJSON", function () {
    const { __v, _id, ...object } = this.toObject();
    object.id = _id;
    return object;
  });
  const appmapping = mongoose.model("appMapping", schema);
  return appmapping;
};
