const dbConfig = require("../config/db.config.js");
const mongoose = require("mongoose");
mongoose.Promise = global.Promise;
const db = {};
db.mongoose = mongoose;
db.url = dbConfig.url;
db.appmapping = require("./appMapping/appMapping")(mongoose);
db.regisDevice = require("./regis_device")(mongoose);
module.exports = db;
